# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3df84c4c1387720d62c1acafe289a11fbcd26720f8c1d56e59df9f2dc7c0e8934dcbbdf9cfd9326ee0c85781bfccd048b5487d300feb70f0c87b087b56924d5f

test:
  secret_key_base: 813647f323a23625a896b1aef116102c0280413003f77b0401e0eefe68e1173c88c72abc2afc2edda719f99a57fbeeb9a92c88666cca344d57fa4a10a6c4501f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
